### ISSUE TITLE
Unable to get app running

### ISSUE THREAD

**Issue by laurenf** [devzero-inc/internal-employee-directory#2]
After running `docker compose up -d` I can see that something is running on port:5173, but the page is blank and I'm getting axios errors in the console.

I also don't see anything at `localhost:8000/test`. In the docker logs, I can see `Server running on port 8000` and `Connected to the database`.

**Comment by TW-Shan** [comment]
Working on this, reproducing the same on local on different OS.

**Comment by AdoshSingh** [comment]
Working on this trying to run it on my local.

**Comment by AdoshSingh** [comment]
I have made the necessary changes, now its working fine, also updated CI to check if the everything is running,
[https://github.com/devzero-inc/internal-employee-directory/actions/runs/8018836841/job/21905574848](https://github.com/devzero-inc/internal-employee-directory/actions/runs/8018836841/job/21905574848)

**Comment by AdoshSingh** [comment]
I have made the necessary changes: 
 - serving the build version in frontend 
 - not installing devDependencies in the docker
 
Also updated CI to check if the everything is up and running,
https://github.com/devzero-inc/internal-employee-directory/actions/runs/8018836841/job/21905574848

**Comment by laurenf** [comment]
Closed: https://github.com/devzero-inc/internal-employee-directory/pull/3
